### ISSUE TITLE
More detail in CFT outputs

### ISSUE THREAD

**Issue by benofben** [neo4j-partners/amazon-cloud-formation-neo4j#35]
I'm updating the SageMaker lab.  That got me thinking that with the LB, we could probably improve the outputs a bit further...

Thinking something like this:

```
Outputs:
  Neo4jBrowserURI:
    Description: URI for Neo4j Browser
    Value: !Join
    - ''
    - - 'http://'
      - !GetAtt Neo4jNetworkLoadBalancer.DNSName
      - ':'
      - '7474'
  Neo4jBoltURI:
    Description: URI for Neo4j Bolt
    Value: !Join
    - ''
    - - 'neo4j://'
      - !GetAtt Neo4jNetworkLoadBalancer.DNSName
      - ':'
      - '7687'
  HelpMessage:
    Description: Help Message
    Value: 'The username is neo4j.  The password is what you provided to the template.  Once the template reports complete, it will take a few minutes for the URIs to become available.'
```
